/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perimetros;

/**
 *
 * @author Norberto
 */
public class JFPerimetros extends javax.swing.JFrame {

    /**
     * Creates new form JFPerimetros
     */
    public JFPerimetros() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxPerimetros = new javax.swing.JComboBox<>();
        jButtonIniciar = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal Perimetros");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBoxPerimetros.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jComboBoxPerimetros.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Círculo", "Cuadrado", "Rectángulo" }));
        getContentPane().add(jComboBoxPerimetros, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 170, 50));

        jButtonIniciar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonIniciar.setText("Iniciar");
        jButtonIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIniciarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 120, 50));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo (1).jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIniciarActionPerformed
        int opciones = jComboBoxPerimetros.getSelectedIndex();

        if (opciones == 0){
            JFPerimetroCirculo circulo = new JFPerimetroCirculo();
            circulo.setVisible(true);
            this.setVisible(false);
        }
        else if (opciones == 1){
            JFPerimetroCuadrado cuadrado = new JFPerimetroCuadrado();
            cuadrado.setVisible(true);
            this.setVisible(false);
        }
        else if (opciones == 2){
            JFPerimetroRectangulo rectangulo = new JFPerimetroRectangulo();
            rectangulo.setVisible(true);
            this.setVisible(false);
        }
                
    }//GEN-LAST:event_jButtonIniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFPerimetros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFPerimetros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFPerimetros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFPerimetros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFPerimetros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIniciar;
    private javax.swing.JComboBox<String> jComboBoxPerimetros;
    private javax.swing.JLabel jLabelFondo;
    // End of variables declaration//GEN-END:variables
}
