/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perimetros;

import javax.swing.JOptionPane;

/**
 *
 * @author Norberto
 */
public class JFPerimetroCirculo extends javax.swing.JFrame {

    /**
     * Creates new form JFPerimetroCirculo
     */
    public JFPerimetroCirculo() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelRadio = new javax.swing.JLabel();
        jTextFieldRadio = new javax.swing.JTextField();
        jLabelFormula = new javax.swing.JLabel();
        jButtonCalcular = new javax.swing.JButton();
        jLabelImagen = new javax.swing.JLabel();
        jButtonCalcular1 = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Perimetro Circulo");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelRadio.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelRadio.setForeground(new java.awt.Color(0, 0, 0));
        jLabelRadio.setText("Radio:");
        getContentPane().add(jLabelRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 90, 30));
        getContentPane().add(jTextFieldRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 200, 30));

        jLabelFormula.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabelFormula.setForeground(new java.awt.Color(0, 0, 0));
        jLabelFormula.setText("P = 2 * Pi * r");
        getContentPane().add(jLabelFormula, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 200, -1));

        jButtonCalcular.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButtonCalcular.setText("Cancelar");
        jButtonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 110, 40));

        jLabelImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/circulo1.png"))); // NOI18N
        getContentPane().add(jLabelImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 140, 140));

        jButtonCalcular1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButtonCalcular1.setText("Calcular");
        jButtonCalcular1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcular1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCalcular1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 200, 40));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo (1).jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularActionPerformed
        JFPerimetros perimetros = new JFPerimetros();
        perimetros.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCalcularActionPerformed

    private void jButtonCalcular1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcular1ActionPerformed
        double radio;
        radio = Double.parseDouble(jTextFieldRadio.getText());
        double perimetroc = 2 * 3.1416 * radio;
        JOptionPane.showMessageDialog(this, "El perimetro del circulo es: " + perimetroc );
    }//GEN-LAST:event_jButtonCalcular1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFPerimetroCirculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFPerimetroCirculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFPerimetroCirculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFPerimetroCirculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFPerimetroCirculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCalcular;
    private javax.swing.JButton jButtonCalcular1;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelFormula;
    private javax.swing.JLabel jLabelImagen;
    private javax.swing.JLabel jLabelRadio;
    private javax.swing.JTextField jTextFieldRadio;
    // End of variables declaration//GEN-END:variables
}
