/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perimetros;

import javax.swing.JOptionPane;

/**
 *
 * @author Norberto
 */
public class JFPerimetroCuadrado extends javax.swing.JFrame {

    /**
     * Creates new form JFPerimetroCirculo
     */
    public JFPerimetroCuadrado() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCancelarCuad = new javax.swing.JButton();
        jButtonCalcularCuad = new javax.swing.JButton();
        jLabelLado = new javax.swing.JLabel();
        jTextFieldLado = new javax.swing.JTextField();
        jLabelFormulaCuad = new javax.swing.JLabel();
        jLabelImagenCuad = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Perimetro Cuadrado");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonCancelarCuad.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButtonCancelarCuad.setText("Cancelar");
        jButtonCancelarCuad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarCuadActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelarCuad, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 110, 40));

        jButtonCalcularCuad.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButtonCalcularCuad.setText("Calcular");
        jButtonCalcularCuad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularCuadActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCalcularCuad, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 200, 40));

        jLabelLado.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelLado.setForeground(new java.awt.Color(0, 0, 0));
        jLabelLado.setText("Lado:");
        getContentPane().add(jLabelLado, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 90, 30));
        getContentPane().add(jTextFieldLado, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 200, 30));

        jLabelFormulaCuad.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabelFormulaCuad.setForeground(new java.awt.Color(0, 0, 0));
        jLabelFormulaCuad.setText("P = 4*L");
        getContentPane().add(jLabelFormulaCuad, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 130, -1));

        jLabelImagenCuad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cuadro.png"))); // NOI18N
        getContentPane().add(jLabelImagenCuad, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 130, 100));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo (1).jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarCuadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarCuadActionPerformed
        JFPerimetros perimetros = new JFPerimetros();
        perimetros.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCancelarCuadActionPerformed

    private void jButtonCalcularCuadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularCuadActionPerformed
        double lado;
        lado = Double.parseDouble(jTextFieldLado.getText());
        double perimetrocua = 4*lado;
        JOptionPane.showMessageDialog(this,"El perimetro del Cuadrado es: " + perimetrocua);
    }//GEN-LAST:event_jButtonCalcularCuadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFPerimetroCuadrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFPerimetroCuadrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFPerimetroCuadrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFPerimetroCuadrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFPerimetroCuadrado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCalcularCuad;
    private javax.swing.JButton jButtonCancelarCuad;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelFormulaCuad;
    private javax.swing.JLabel jLabelImagenCuad;
    private javax.swing.JLabel jLabelLado;
    private javax.swing.JTextField jTextFieldLado;
    // End of variables declaration//GEN-END:variables
}
