/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perimetros;

import javax.swing.JOptionPane;

/**
 *
 * @author Norberto
 */
public class JFPerimetroRectangulo extends javax.swing.JFrame {

    /**
     * Creates new form JFPerimetroCirculo
     */
    public JFPerimetroRectangulo() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCancelarRec = new javax.swing.JButton();
        jButtonCalcularRec = new javax.swing.JButton();
        jLabelFormulaRec = new javax.swing.JLabel();
        jTextFieldBaseRec = new javax.swing.JTextField();
        jLabelAlturaRec = new javax.swing.JLabel();
        jLabelImagenRec = new javax.swing.JLabel();
        jTextFieldAlturaRec = new javax.swing.JTextField();
        jLabelBaseRec1 = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Perimetro Rectangulo");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonCancelarRec.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButtonCancelarRec.setText("Cancelar");
        jButtonCancelarRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarRecActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelarRec, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 110, 40));

        jButtonCalcularRec.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButtonCalcularRec.setText("Calcular");
        jButtonCalcularRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularRecActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCalcularRec, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 200, 40));

        jLabelFormulaRec.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabelFormulaRec.setForeground(new java.awt.Color(0, 0, 0));
        jLabelFormulaRec.setText("P = 2(a+b)");
        getContentPane().add(jLabelFormulaRec, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 180, 30));

        jTextFieldBaseRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBaseRecActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldBaseRec, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 200, -1));

        jLabelAlturaRec.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelAlturaRec.setForeground(new java.awt.Color(0, 0, 0));
        jLabelAlturaRec.setText("Altura:");
        getContentPane().add(jLabelAlturaRec, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 90, 20));

        jLabelImagenRec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/RECTANGULO.png"))); // NOI18N
        getContentPane().add(jLabelImagenRec, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 140, 90));
        getContentPane().add(jTextFieldAlturaRec, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 200, -1));

        jLabelBaseRec1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelBaseRec1.setForeground(new java.awt.Color(0, 0, 0));
        jLabelBaseRec1.setText("Base:");
        getContentPane().add(jLabelBaseRec1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 90, 20));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo (1).jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarRecActionPerformed
        JFPerimetros perimetros = new JFPerimetros();
        perimetros.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCancelarRecActionPerformed

    private void jTextFieldBaseRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBaseRecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBaseRecActionPerformed

    private void jButtonCalcularRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularRecActionPerformed
        double base;
        double altura;
        base = Double.parseDouble(jTextFieldBaseRec.getText());
        altura = Double.parseDouble(jTextFieldAlturaRec.getText());
        double perimetror = 2*(base + altura);
        JOptionPane.showMessageDialog(this,"El perimetro del Rectangulo es: " + perimetror);
    }//GEN-LAST:event_jButtonCalcularRecActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFPerimetroRectangulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFPerimetroRectangulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFPerimetroRectangulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFPerimetroRectangulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFPerimetroRectangulo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCalcularRec;
    private javax.swing.JButton jButtonCancelarRec;
    private javax.swing.JLabel jLabelAlturaRec;
    private javax.swing.JLabel jLabelBaseRec1;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelFormulaRec;
    private javax.swing.JLabel jLabelImagenRec;
    private javax.swing.JTextField jTextFieldAlturaRec;
    private javax.swing.JTextField jTextFieldBaseRec;
    // End of variables declaration//GEN-END:variables
}
