
package MayorMenor; 

import javax.swing.JOptionPane;



/**
 *
 * @author Norberto
 */
public class JFrame_Comparacion extends javax.swing.JFrame {

    /**
     * Creates new form JFrame_Comparacion
     */
    public JFrame_Comparacion() {
        initComponents();
        setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        opciones = new javax.swing.ButtonGroup();
        jLabelNumero1 = new javax.swing.JLabel();
        jLabelNumero2 = new javax.swing.JLabel();
        jLabelNumero3 = new javax.swing.JLabel();
        jTextFieldNumero1 = new javax.swing.JTextField();
        jTextFieldNumero2 = new javax.swing.JTextField();
        jTextFieldNumero3 = new javax.swing.JTextField();
        jRadioButtonMenor = new javax.swing.JRadioButton();
        jRadioButtonMayor = new javax.swing.JRadioButton();
        jButtonComparar = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelNumero1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelNumero1.setForeground(new java.awt.Color(0, 0, 0));
        jLabelNumero1.setText("Número 1:");
        getContentPane().add(jLabelNumero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 100, 30));

        jLabelNumero2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelNumero2.setForeground(new java.awt.Color(0, 0, 0));
        jLabelNumero2.setText("Número 2:");
        getContentPane().add(jLabelNumero2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 100, 30));

        jLabelNumero3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelNumero3.setForeground(new java.awt.Color(0, 0, 0));
        jLabelNumero3.setText("Número 3:");
        getContentPane().add(jLabelNumero3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 100, 30));

        jTextFieldNumero1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTextFieldNumero1.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldNumero1.setText("0.0");
        getContentPane().add(jTextFieldNumero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 120, 30));

        jTextFieldNumero2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTextFieldNumero2.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldNumero2.setText("0.0");
        getContentPane().add(jTextFieldNumero2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 120, 30));

        jTextFieldNumero3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTextFieldNumero3.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldNumero3.setText("0.0");
        getContentPane().add(jTextFieldNumero3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 120, 30));

        opciones.add(jRadioButtonMenor);
        jRadioButtonMenor.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jRadioButtonMenor.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButtonMenor.setText("Menor");
        getContentPane().add(jRadioButtonMenor, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 90, -1));

        opciones.add(jRadioButtonMayor);
        jRadioButtonMayor.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jRadioButtonMayor.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButtonMayor.setText("Mayor");
        jRadioButtonMayor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMayorActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonMayor, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 90, -1));

        jButtonComparar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonComparar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonComparar.setText("Comparar");
        jButtonComparar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCompararMouseClicked(evt);
            }
        });
        jButtonComparar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCompararActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonComparar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 120, 60));
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCompararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCompararActionPerformed
        
    }//GEN-LAST:event_jButtonCompararActionPerformed

    private void jButtonCompararMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCompararMouseClicked
        float numero1;
        float numero2;
        float numero3;
        
        numero1 = Float.parseFloat(this.jTextFieldNumero1.getText());
        numero2 = Float.parseFloat(this.jTextFieldNumero2.getText());
        numero3 = Float.parseFloat(this.jTextFieldNumero3.getText());
        
        if(jRadioButtonMayor.isSelected()){
            if (numero1 > numero2 && numero1 > numero3) {
                JOptionPane.showMessageDialog(this, "El numero Mayor es: " + numero1);
            }
            else if(numero2 > numero1 && numero2 > numero3) {
                JOptionPane.showMessageDialog(this, "El numero Mayor es: " + numero2);
            }
            else if(numero3 > numero1 && numero3 > numero2) {
                JOptionPane.showMessageDialog(this, "El numero Mayor es: " + numero3);
            }
            else if(numero1 > numero2 && numero1 == numero3){
                JOptionPane.showMessageDialog(this, "El numero Mayor es: " + numero1);
            }
            else if(numero1 == numero2 && numero1 > numero3){
                JOptionPane.showMessageDialog(this, "El numero Mayor es: " + numero1);
            }
            else if(numero2 > numero1 && numero2 == numero3){
                JOptionPane.showMessageDialog(this, "El numero Mayor es: " + numero2);
            }
            else if(numero2 == numero1 && numero2 > numero3){
                JOptionPane.showMessageDialog(this, "El numero Mayor es: " + numero2);
            }
            else if(numero3 > numero1 && numero3 == numero2){
                JOptionPane.showMessageDialog(this, "El numero Mayor es: " + numero2);
            }
            else if(numero3 == numero1 && numero3 > numero2){
                JOptionPane.showMessageDialog(this, "El numero Mayor es: " + numero2);
            }
            else {
                JOptionPane.showMessageDialog(this, "Todos los numeros son iguales");
            }
        }
        else if(jRadioButtonMenor.isSelected()){
            if (numero1 < numero2 && numero1 < numero3) {
                JOptionPane.showMessageDialog(this, "El numero Menor es: " + numero1);
            }
            else if(numero2 < numero1 && numero2 < numero3) {
                JOptionPane.showMessageDialog(this, "El numero Menor es: " + numero2);
            }
            else if(numero3 < numero1 && numero3 < numero2) {
                JOptionPane.showMessageDialog(this, "El numero Menor es: " + numero3);
            }
            else if(numero1 < numero2 && numero1 == numero3){
                JOptionPane.showMessageDialog(this, "El numero Menor es: " + numero1);
            }
            else if(numero1 == numero2 && numero1 < numero3){
                JOptionPane.showMessageDialog(this, "El numero Menor es: " + numero1);
            }
            else if(numero2 < numero1 && numero2 == numero3){
                JOptionPane.showMessageDialog(this, "El numero Menor es: " + numero2);
            }
            else if(numero2 == numero1 && numero2 < numero3){
                JOptionPane.showMessageDialog(this, "El numero Menor es: " + numero2);
            }
            else if(numero3 < numero1 && numero3 == numero2){
                JOptionPane.showMessageDialog(this, "El numero Menor es: " + numero2);
            }
            else if(numero3 == numero1 && numero3 < numero2){
                JOptionPane.showMessageDialog(this, "El numero Menor es: " + numero2);
            }
            else {
                JOptionPane.showMessageDialog(this, "Todos los numeros son iguales");
            }
        }
    }//GEN-LAST:event_jButtonCompararMouseClicked

    private void jRadioButtonMayorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMayorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonMayorActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_Comparacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_Comparacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_Comparacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_Comparacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_Comparacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonComparar;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelNumero1;
    private javax.swing.JLabel jLabelNumero2;
    private javax.swing.JLabel jLabelNumero3;
    private javax.swing.JRadioButton jRadioButtonMayor;
    private javax.swing.JRadioButton jRadioButtonMenor;
    private javax.swing.JTextField jTextFieldNumero1;
    private javax.swing.JTextField jTextFieldNumero2;
    private javax.swing.JTextField jTextFieldNumero3;
    private javax.swing.ButtonGroup opciones;
    // End of variables declaration//GEN-END:variables
}
