/*
 * EVENTO CLICK JB_Sumar
    1._ Crear una variable flotante numero1
    2._ Crear  una variable flotante numero2
    3._ Convertir el texto de JTF_numero1 a flotante y guardar en numero1
    4._ Convertir el texto de jtf_Numero2 a flotante y guardarlo en numero 2
    5._ Crear una variable flotante reultado y guardar la suma de numero1 y numero2
    6._ Mostrar en JTF_Resultado
 */
package Calculadora;

import javafx.scene.control.ComboBox;

/**
 *
 * @author Norberto
 */
public class JFCaluladora extends javax.swing.JFrame {

    /**
     * Creates new form Caluladora
     */
    public JFCaluladora() {
        initComponents();
        setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton7 = new javax.swing.JButton();
        jLabelNumeroUno = new javax.swing.JLabel();
        jLabelNumeroDos = new javax.swing.JLabel();
        jLabelResultado = new javax.swing.JLabel();
        jTextFieldNumeroUno = new javax.swing.JTextField();
        jTextFieldNumeroDos = new javax.swing.JTextField();
        jTextFieldResultado = new javax.swing.JTextField();
        jButtonSuma = new javax.swing.JButton();
        jButtonResta = new javax.swing.JButton();
        jButtonResiduo = new javax.swing.JButton();
        jButtonDivision = new javax.swing.JButton();
        jButtonMultiplicacion = new javax.swing.JButton();
        jButtonLimpiar = new javax.swing.JButton();
        jLabelImagen = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jButton7.setText("jButton7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelNumeroUno.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabelNumeroUno.setText("Número 1:");
        getContentPane().add(jLabelNumeroUno, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabelNumeroDos.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabelNumeroDos.setText("Número 2:");
        getContentPane().add(jLabelNumeroDos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabelResultado.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabelResultado.setText("Resultado:");
        getContentPane().add(jLabelResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jTextFieldNumeroUno.setText("0.0");
        getContentPane().add(jTextFieldNumeroUno, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 20, 167, -1));

        jTextFieldNumeroDos.setText("0.0");
        getContentPane().add(jTextFieldNumeroDos, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 60, 167, -1));

        jTextFieldResultado.setText("0.0");
        getContentPane().add(jTextFieldResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 100, 166, -1));

        jButtonSuma.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButtonSuma.setText("+");
        jButtonSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSumaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSuma, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 148, -1, -1));

        jButtonResta.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButtonResta.setText("-");
        jButtonResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRestaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonResta, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 148, -1, -1));

        jButtonResiduo.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButtonResiduo.setText("%");
        jButtonResiduo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResiduoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonResiduo, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 148, -1, -1));

        jButtonDivision.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButtonDivision.setText("/");
        jButtonDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDivisionActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDivision, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 190, -1, -1));

        jButtonMultiplicacion.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButtonMultiplicacion.setText("*");
        jButtonMultiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMultiplicacionActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMultiplicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 190, -1, -1));

        jButtonLimpiar.setFont(new java.awt.Font("Trebuchet MS", 1, 10)); // NOI18N
        jButtonLimpiar.setText("Limpiar");
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 191, -1, 27));

        jLabelImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/IconoCalculadora.png"))); // NOI18N
        getContentPane().add(jLabelImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 240));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSumaActionPerformed
        float numero1 = 0.0f;//Variable numero1
        float numero2 = 0.0f;//Variable numero2
        numero1 = Float.parseFloat(this.jTextFieldNumeroUno.getText()); //Convierte el texto a flotante y guarda el numero1
        numero2 = Float.parseFloat(this.jTextFieldNumeroDos.getText()); //Convierte el texto a flotante y guarda el numero2
        float resultado = numero1 + numero2; //Se crea una variable flotante "Resultado" y se guarda la suma
        this.jTextFieldResultado.setText(String.valueOf(resultado)); // Mostrar resultado en JTextFieldResultado el resultado
    }//GEN-LAST:event_jButtonSumaActionPerformed

    private void jButtonMultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMultiplicacionActionPerformed
        float numero1 = 0.0f;//Variable numero1
        float numero2 = 0.0f;//Variable numero2
        numero1 = Float.parseFloat(this.jTextFieldNumeroUno.getText());//Convierte texto a flotante
        numero2 = Float.parseFloat(this.jTextFieldNumeroDos.getText());//Y guarda numero1 y numero2
        float resultado = numero1 * numero2;
        this.jTextFieldResultado.setText(String.valueOf(resultado));
    }//GEN-LAST:event_jButtonMultiplicacionActionPerformed

    private void jButtonRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRestaActionPerformed
        float numero1 = 0.0f;//Variable numero1
        float numero2 = 0.0f;//Variable numero2
        numero1 = Float.parseFloat(this.jTextFieldNumeroUno.getText());//Convierte texto a flotante
        numero2 = Float.parseFloat(this.jTextFieldNumeroDos.getText());
        float resultado = numero1 - numero2;
        this.jTextFieldResultado.setText(String.valueOf(resultado));
    }//GEN-LAST:event_jButtonRestaActionPerformed

    private void jButtonResiduoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResiduoActionPerformed
        float numero1 = 0.0f;//Variable numero1
        float numero2 = 0.0f;//Variable numero2
        numero1 = Float.parseFloat(this.jTextFieldNumeroUno.getText());//Convierte texto a flotante
        numero2 = Float.parseFloat(this.jTextFieldNumeroDos.getText());//Y guarda numero1 y numero2
        float resultado = numero1 % numero2;
        this.jTextFieldResultado.setText(String.valueOf(resultado));
    }//GEN-LAST:event_jButtonResiduoActionPerformed

    private void jButtonDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDivisionActionPerformed
        float numero1 = 0.0f;//Variable numero1
        float numero2 = 0.0f;//Variable numero2
        numero1 = Float.parseFloat(this.jTextFieldNumeroUno.getText());//Convierte texto a flotante
        numero2 = Float.parseFloat(this.jTextFieldNumeroDos.getText());//Y guarda numero1 y numero2
        float resultado = numero1 / numero2;
        this.jTextFieldResultado.setText(String.valueOf(resultado));
    }//GEN-LAST:event_jButtonDivisionActionPerformed

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed
        jTextFieldNumeroUno.setText("0.0");
        jTextFieldNumeroDos.setText("0.0");
        jTextFieldResultado.setText("0.0");
    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFCaluladora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFCaluladora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFCaluladora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFCaluladora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFCaluladora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButtonDivision;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JButton jButtonMultiplicacion;
    private javax.swing.JButton jButtonResiduo;
    private javax.swing.JButton jButtonResta;
    private javax.swing.JButton jButtonSuma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelImagen;
    private javax.swing.JLabel jLabelNumeroDos;
    private javax.swing.JLabel jLabelNumeroUno;
    private javax.swing.JLabel jLabelResultado;
    private javax.swing.JTextField jTextFieldNumeroDos;
    private javax.swing.JTextField jTextFieldNumeroUno;
    private javax.swing.JTextField jTextFieldResultado;
    // End of variables declaration//GEN-END:variables
}
