package CalcV2;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Norberto
 */
public class JF_Caluladorav2 extends javax.swing.JFrame {

    /**
     * Creates new form Caluladorav2
     */
    public JF_Caluladorav2() {
        initComponents();
        setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelResultado = new javax.swing.JLabel();
        jLabelNumero1 = new javax.swing.JLabel();
        jLabelNumero2 = new javax.swing.JLabel();
        jTextFieldNumero2 = new javax.swing.JTextField();
        jTextFieldNumero1 = new javax.swing.JTextField();
        jComboBoxOperaciones = new javax.swing.JComboBox<>();
        jButtonCalcular = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelResultado.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabelResultado.setText("0.0");
        getContentPane().add(jLabelResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 210, 20));

        jLabelNumero1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelNumero1.setText("Número 1:");
        getContentPane().add(jLabelNumero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        jLabelNumero2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelNumero2.setText("Número 2:");
        getContentPane().add(jLabelNumero2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, 20));

        jTextFieldNumero2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTextFieldNumero2.setText("0.0");
        getContentPane().add(jTextFieldNumero2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 120, -1));

        jTextFieldNumero1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTextFieldNumero1.setText("0.0");
        getContentPane().add(jTextFieldNumero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 120, -1));

        jComboBoxOperaciones.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jComboBoxOperaciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Suma", "Resta", "Multiplicación", "División", "Modulo" }));
        jComboBoxOperaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxOperacionesActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxOperaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, 40));

        jButtonCalcular.setText("Calcular");
        jButtonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, -1, 40));
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularActionPerformed
        float numero1 = 0.0f;
        float numero2 = 0.0f;

        numero1 = Float.parseFloat(jTextFieldNumero1.getText());
        numero2 = Float.parseFloat(jTextFieldNumero2.getText());

        int operacion = jComboBoxOperaciones.getSelectedIndex();

        if (operacion == 0) 
            {
                jLabelResultado.setText(String.valueOf(numero1 + numero2));
            }
        
        else if(operacion == 1)
            {
                jLabelResultado.setText(String.valueOf(numero1 - numero2));
            }
            
        else if(operacion == 2)
            {
                jLabelResultado.setText(String.valueOf(numero1 * numero2));
            }
        else if(operacion == 3)
            {
                jLabelResultado.setText(String.valueOf(numero1 / numero2));
            }
        else if(operacion == 4)
                {
                    jLabelResultado.setText(String.valueOf(numero1 % numero2));
                }
    }//GEN-LAST:event_jButtonCalcularActionPerformed
      
    private void jComboBoxOperacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxOperacionesActionPerformed

    }//GEN-LAST:event_jComboBoxOperacionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_Caluladorav2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_Caluladorav2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_Caluladorav2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_Caluladorav2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new JF_Caluladorav2().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCalcular;
    private javax.swing.JComboBox<String> jComboBoxOperaciones;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelNumero1;
    private javax.swing.JLabel jLabelNumero2;
    private javax.swing.JLabel jLabelResultado;
    private javax.swing.JTextField jTextFieldNumero1;
    private javax.swing.JTextField jTextFieldNumero2;
    // End of variables declaration//GEN-END:variables
}
